name: 'Build PiRogue OS'
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out ğŸ›ï¸
      uses: actions/checkout@v2

    - name: Prepare host ğŸ”§
      run: "apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc qemu-utils kpartx gpg"

    - name: Build ğŸ”§
      run: "bash build.sh -c config"

    - name: Upload artifacts ğŸš€
      uses: actions/upload-artifact@v2
      with:
        name: PiRogueOS
        path: deploy/*