name: 'Build PiRogue OS'
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out ğŸ›ï¸
      uses: actions/checkout@v2

    - name: Build ğŸ”§
      run: "bash build-docker.sh -c config"

    - name: Upload artifacts ğŸš€
      uses: actions/upload-artifact@v2
      with:
        name: PiRogueOS
        path: deploy/*